#pragma once

#include <JuceHeader.h>
#include "Config.h"

//==============================================================================

struct ControllerObject
{
    int x = 0;
    int y = 0;
    int w = 0;
    int h = 0;
    int minValue = 0;
    int maxValue = 127;
    bool isEditingMode = false;
    juce::String tabId; // tab id (generated by UUID) where the object is created on
    Config::MidiType midiType;
    juce::Colour color = juce::Colours::coral;
    juce::String id; // exadecimal ID generated by UUID
    int midiChannel = 1; // midi channel
    int ccNumber; // cc number like cc11
    int ccValue; // cc value like 127
    int noteNumber; // midi note to send to
};